create table if not exists public.math_abc_grade_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  problem_id text not null,
  created_at timestamptz not null default now()
);

alter table public.math_abc_grade_usage
  drop constraint if exists math_abc_grade_usage_problem_id_check;
alter table public.math_abc_grade_usage
  add constraint math_abc_grade_usage_problem_id_check
  check (problem_id ~ '^(MABC[0-9]{3}|L[1-3]-[0-9]{3})-[A-E]$');

create index if not exists math_abc_grade_usage_user_created_idx
  on public.math_abc_grade_usage (user_id, created_at desc);

alter table public.math_abc_grade_usage enable row level security;
revoke all on table public.math_abc_grade_usage from anon, authenticated;
revoke all on sequence public.math_abc_grade_usage_id_seq from anon, authenticated;
grant select, insert, delete on table public.math_abc_grade_usage to service_role;
grant usage, select on sequence public.math_abc_grade_usage_id_seq to service_role;
