create table if not exists public.math_abc_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  problem_id text not null,
  status text not null check (status in ('AC', 'REVIEW', 'WA')),
  best_score integer not null default 0 check (best_score between 0 and 100),
  attempts integer not null default 0 check (attempts >= 0),
  last_answer text not null default '',
  duration_seconds integer not null default 0 check (duration_seconds >= 0),
  first_status text check (first_status in ('AC', 'REVIEW', 'WA')),
  first_score integer check (first_score between 0 and 100),
  ac_attempt integer check (ac_attempt > 0),
  solved_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (user_id, problem_id)
);

create index if not exists math_abc_progress_updated_at_idx
  on public.math_abc_progress (user_id, updated_at desc);

alter table public.math_abc_progress enable row level security;

drop policy if exists "Users can read own Math ABC progress" on public.math_abc_progress;
create policy "Users can read own Math ABC progress"
  on public.math_abc_progress for select to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert own Math ABC progress" on public.math_abc_progress;
create policy "Users can insert own Math ABC progress"
  on public.math_abc_progress for insert to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update own Math ABC progress" on public.math_abc_progress;
create policy "Users can update own Math ABC progress"
  on public.math_abc_progress for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete own Math ABC progress" on public.math_abc_progress;
create policy "Users can delete own Math ABC progress"
  on public.math_abc_progress for delete to authenticated
  using ((select auth.uid()) = user_id);

revoke all on table public.math_abc_progress from anon, authenticated;
grant select, insert, update, delete on table public.math_abc_progress to authenticated;

create table if not exists public.math_abc_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  problem_id text not null,
  status text not null check (status in ('AC', 'REVIEW', 'WA')),
  score integer not null check (score between 0 and 100),
  answer text not null default '',
  answer_type text not null default 'text' check (answer_type in ('text', 'text_photo')),
  image_path text,
  duration_seconds integer not null default 0 check (duration_seconds >= 0),
  created_at timestamptz not null default now()
);

create index if not exists math_abc_attempts_user_created_idx
  on public.math_abc_attempts (user_id, created_at desc);
create index if not exists math_abc_attempts_problem_idx
  on public.math_abc_attempts (user_id, problem_id, created_at desc);

alter table public.math_abc_attempts enable row level security;

drop policy if exists "Users can read own Math ABC attempts" on public.math_abc_attempts;
create policy "Users can read own Math ABC attempts"
  on public.math_abc_attempts for select to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert own Math ABC attempts" on public.math_abc_attempts;
create policy "Users can insert own Math ABC attempts"
  on public.math_abc_attempts for insert to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete own Math ABC attempts" on public.math_abc_attempts;
create policy "Users can delete own Math ABC attempts"
  on public.math_abc_attempts for delete to authenticated
  using ((select auth.uid()) = user_id);

revoke all on table public.math_abc_attempts from anon, authenticated;
grant select, insert, delete on table public.math_abc_attempts to authenticated;
grant usage, select on sequence public.math_abc_attempts_id_seq to authenticated;

create table if not exists public.math_abc_grade_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  problem_id text not null check (problem_id ~ '^MABC[0-9]{3}-[A-E]$'),
  created_at timestamptz not null default now()
);

create index if not exists math_abc_grade_usage_user_created_idx
  on public.math_abc_grade_usage (user_id, created_at desc);

alter table public.math_abc_grade_usage enable row level security;
revoke all on table public.math_abc_grade_usage from anon, authenticated;
revoke all on sequence public.math_abc_grade_usage_id_seq from anon, authenticated;
grant select, insert, delete on table public.math_abc_grade_usage to service_role;
grant usage, select on sequence public.math_abc_grade_usage_id_seq to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'math-abc-answers',
  'math-abc-answers',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Users can upload own Math ABC answer images" on storage.objects;
create policy "Users can upload own Math ABC answer images"
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'math-abc-answers'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "Users can read own Math ABC answer images" on storage.objects;
create policy "Users can read own Math ABC answer images"
  on storage.objects for select to authenticated
  using (
    bucket_id = 'math-abc-answers'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "Users can update own Math ABC answer images" on storage.objects;
create policy "Users can update own Math ABC answer images"
  on storage.objects for update to authenticated
  using (
    bucket_id = 'math-abc-answers'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  )
  with check (
    bucket_id = 'math-abc-answers'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "Users can delete own Math ABC answer images" on storage.objects;
create policy "Users can delete own Math ABC answer images"
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'math-abc-answers'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );
